name: Linux Realse
on:
  push:
    tags: [ "*release", "*release-linux" ]

env:
  RELEASE_ARCHIVE_NAME: utas-release

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Run tests
      run: cargo test --verbose

    - name: Run crate file tests
      run: cargo test -p file

  linux-build-release:
    runs-on: ubuntu-latest
    needs:  tests
    permissions:
       contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Build
      run: cargo build --release --verbose

    - name: Compress assets
      run: |
        cd target
        tar cfv "$RELEASE_ARCHIVE_NAME"-linux.tar.gz release/utas

    - name: Create release and upload assets
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ github.ref_name }}
        name: Utas-Linux release ${{ github.ref_name }}
        draft: true
        prerelease: false
        files: target/${{ env.RELEASE_ARCHIVE_NAME }}-linux.tar.gz
