name: MacOs Release
on:
  push:
    tags: [ "*release", "*release-mac" ]

env:
  RELEASE_ARCHIVE_NAME: utas-release

jobs:
  tests:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Run tests
      run: cargo test --verbose

    - name: Run crate file tests
      run: cargo test -p file

  mac-build-release:
    runs-on: macos-latest
    needs:  tests
    permissions:
       contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Build
      run: cargo build --release --verbose

    - name: Compress assets
      run: |
        cd target
        zip -r "$RELEASE_ARCHIVE_NAME"-mac-os.zip release/utas

    - name: Create release and upload assets
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ github.ref_name }}
        name: Utas-MacOs release ${{ github.ref_name }}
        draft: true
        prerelease: false
        files: target/${{ env.RELEASE_ARCHIVE_NAME }}-mac-os.zip
